;;; Compiled snippets and support files for `rhtml-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'rhtml-mode
                     '(("%" "<%$0 %>\n" "<%$. %>" nil nil nil nil nil nil)
                       ("%%" "<%=$0 %>\n" "<%=$. %>" nil nil nil nil nil nil)
                       ("%ff" "<%= form_for @${1:attribute} ${2: :action => \"${3:create}\"} do |f| %>\n  $0\n  <%= f.submit \"Create\" %>\n<% end %>\n" "<%= form_for ... do |f| %>" nil nil nil nil nil nil)
                       ("%ffe" "<%= form_for @$1 do |f| %>\n  <% if @$1.errors.any? %>\n    <div class=\"error_messages\">\n      <h2>Form is invalid</h2>\n      <ul>\n        <% for message in @$1.errors.full_messages %>\n          <li><%= message %></li>\n        <% end %>\n      </ul>\n    </div>\n  <% end %>\n  $0\n  <p class=\"button\"><%= f.submit %></p>\n<% end %>\n" "<%= form_for @var do |f| ... if @var.errors.only? ... %>" nil nil nil nil nil nil)
                       ("%ffld" "<p>\n  <%= f.label :$1 %><br />\n  <%= f.text_field :$1 %>\n</p>\n" "<p><%= f.label ... %> ... <%= f.text_field ... %></p>" nil nil nil nil nil nil)
                       ("%fld" "<p>\n  <%= label_tag :$1 %><br />\n  <%= text_field_tag :$1 %>\n</p>\n" "<p><%= label_tag ... %> ... <%= text_field_tag ... %></p>" nil nil nil nil nil nil)
                       ("%ft" "<%= form_tag ${1:url} do %>\n  $0\n  <p class=\"button\"><%= submit_tag %></p>\n<% end %>\n" "<%= form_tag url do %> ... <% end  %>" nil nil nil nil nil nil)
                       ("%h" "<%=h ${@item} %>\n" "<%=h  ...  %>" nil nil nil nil nil nil)
                       ("%if" "<% if ${1:cond} %>\n  $0\n<% end %>\n" "<% if  ...  %> $. <% end %>" nil nil nil nil nil nil)
                       ("%ife" "<% if ${1:condition} %>\n  $2\n<% else %>\n  $0\n<% end %>\n" "<% if  ...  %> $. <% else %> <% end %>" nil nil nil nil nil nil)
                       ("%lia" "<%= link_to \"${title}\", :action => \"${index}\" %>$0" "<%= link_to \" ... \", :action => \" ... \" %>" nil nil nil nil nil nil)
                       ("%liai" "<%= link_to \"${title}\", :action => \"${edit}\", :id => ${@item} %>$0" "<%= link_to \" ... \", :action => \" ... \", :id =>  ...  %>" nil nil nil nil nil nil)
                       ("%lic" "<%= link_to \"${title}\", :controller => \"${items}\" %>$0" "<%= link_to \" ... \", :controller => \" ... \" %>" nil nil nil nil nil nil)
                       ("%lica" "<%= link_to \"${title}\", :controller => \"${items}\", :action => \"${index}\" %>$0" "<%= link_to \" ... \", :controller => \" ... \", :action => \" ... \" %>" nil nil nil nil nil nil)
                       ("%licai" "<%= link_to \"${title}\", :controller => \"${items}\", :action => \"${edit}\", :id => ${@item} %>$0" "<%= link_to \" ... \", :controller => \" ... \", :action => \" ... \", :id =>  ...  %>" nil nil nil nil nil nil)
                       ("%lip" "<%= link_to \"${title}\", ${items}_path %>$0\n" "<%= link_to \" ... \", \"...\"_path %>" nil nil nil nil nil nil)
                       ("%rp" "<%= render(:partial => \"${action}\"$0 ) %>" "<%= render(:partial => ... ) %>" nil nil nil nil nil nil)
                       ("%ta" "<%= text_area(\"${object_name}\", \"${method}\"$0) %>\n" "<%= text_area(\" ... \", \" ... \") %>" nil nil nil nil nil nil)
                       ("%tf" "<%= text_field(\"${object_name} \", \"${method}\"$0) %>" "<%= text_field(\" ... \", \" ... \") %>" nil nil nil nil nil nil)
                       ("%unless" "<% unless ${cond} -%>\n$0\n<% end -%>\n" "<% unless  ...  -%> $. <% end -%>" nil nil nil nil nil nil)
                       ("nc" "ng-click=\"$0()\" " "ng-click=\"...\"" nil nil nil nil nil nil)
                       ("script" "<script src='//maps.googleapis.com/maps/api/js?sensor=false'></script>\n<script src=\"https://rawgithub.com/nlaplante/angular-google-maps/master/dist/angular-google-maps.min.js\"></script>\n" "<script src=\"angular-google-map.js\">...</script>" nil nil nil nil nil nil)
                       ("nl" "\\{\\{ $0 \\}\\}" "{{ angular-label }}" nil nil nil nil nil nil)
                       ("nr" "ng-repeat=\"i in ${0:items}\" " "ng-repeat=\"...\"" nil nil nil nil nil nil)
                       ("btn" "<button>$1</button>\n" "button" nil nil nil nil nil nil)
                       ("button3column" "<style type=\"text/css\" media=\"screen\">\n.${1:prefix}_button3Column {\n}\n\n.${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3Column .${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnMiddle {\n  float:left;\n  display:inline-block;\n  background-color:${2:blue};\n  white-space:nowrap;\n  height:${3:30}px;\n  line-height:${3:$(yas-substr yas-text \"[0-9]*\")}px;\n  text-align:center;\n}\n\n.${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3Column .${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnLeft {\n  float:left;\n  display:inline-block;\n  width:${4:20}px;\n  height:${3:$(yas-substr yas-text \"[0-9]*\")}px;\n}\n\n.${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3Column .${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnRight {\n  float:left;\n  display:inline-block;\n  width:${5:20}px;\n  height:${3:$(yas-substr yas-text \"[0-9]*\")}px;\n}\n</style>\n<div class='${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3Column'>\n  <div class='${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnLeft'></div>\n  <div class='${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnMiddle'><a href='#'>$0</a></div>\n  <div class='${1:$(yas-substr yas-text \"[a-zA-Z0-9]*\")}_button3ColumnRight'></div>\n</div>" "three column button" nil nil nil nil nil nil)
                       ("css" "<link rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap${1:.min}.css\" />" "<link href=\"bootstrap.css\" />" nil nil nil nil nil nil)
                       ("css" "<style type=\"text/css\">\n  $0\n</style>" "<style type=\"text/css\">...</style>" nil nil nil nil nil nil)
                       ("div" "<div class=\"${1:className}\">\n  $0\n</div>\n" "div" nil nil nil nil nil nil)
                       ("fieldset" "<fieldset class=\"${1:ClassName}\"}>\n<legend>${2:`yas/selected-text`}</legend>\n\n$0\n</fieldset>" "Fieldset" nil nil nil nil nil nil)
                       ("form" "<form method=\"${1:post}\" id=\"$2\" action=\"$3\">\n<fieldset><legend>${4:formTitle}</legend>\n<p>\n<label for=\"${5:ctrlid}\">${5:labelText}</label>\n<input id=\"${5:$(yas/substr yas-text \"[^ ]*\")}\" name=\"${5:$(yas/substr yas-text \"[^ ]*\")}\" type=\"text\" />\n</p>\n  $0\n</fieldset>\n</form>\n" "<form><fieldset><p><label><input></p></fieldset></form>" nil nil nil nil nil nil)
                       ("foundation" "<!DOCTYPE html>\n<!--[if IE 8]> 				 <html class=\"no-js lt-ie9\" lang=\"en\" > <![endif]-->\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"en\" > <!--<![endif]-->\n\n<head>\n  <meta charset=\"utf-8\" />\n  <meta name=\"viewport\" content=\"width=device-width\" />\n  <title>${1:Test foundation.css}</title>\n  <script src=\"//cdnjs.cloudflare.com/ajax/libs/modernizr/2.6.2/modernizr.min.js\"></script>\n  <link rel=\"stylesheet\" href=\"http://cdnjs.cloudflare.com/ajax/libs/foundation/4.1.6/css/foundation.css\" />\n</head>\n<body>\n  <script>window.jQuery || document.write('<script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.2/jquery.min.js\"><\\/script>')</script>\n  <script src=\"http://cdnjs.cloudflare.com/ajax/libs/foundation/4.1.6/js/foundation.min.js\"></script>\n  <a href=\"#\" class=\"button success\">Success Button</a>\n  $0\n  <script>\n  $(document).ready(function(){\n    $(document).foundation();\n    //insert code below this line\n  });\n</script>\n</body>\n</html>" "<html>foudation html ...</html>" nil nil nil nil nil nil)
                       ("html5" "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta name=\"description\" content=\"\" />\n    <title>${1:mytitle}</title>\n    <style type=\"text/css\"></style>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js\"></script>\n    <script type=\"text/javascript\">\n      Modernizr.load([{\n        test: Modernizr.mq('only all'),\n        nope: '//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js'\n      }]);\n    </script>\n  </head>\n  <body>\n    $0\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.2/jquery.js\"></script>\n    <script type=\"text/javascript\">\n      $(document).ready(function (){\n        alert(\"jquery is working\");\n      });\n    </script>\n  </body>\n</html>\n" "<!DOCTYPE html><html>...</html>" nil nil nil nil nil nil)
                       ("html5" "<!DOCTYPE html>\n<html ng-app=\"myApp\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta name=\"description\" content=\"\" />\n    <title>Angular Sandbox (with Bootstrap)</title>\n    <script src=\"//cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.20/angular.min.js\"></script>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.11.2/ui-bootstrap-tpls.min.js\"></script>\n    <link type=\"text/css\" rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css\" />\n	<link type=\"text/css\" rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css\" />\n    <style type=\"text/css\">.nav, .pagination, .carousel, .panel-title a { cursor: pointer; } /* angular ui bootstrap hack */</style>\n  </head>\n  <body>\n    <div class=\"row\">\n      <div class=\"col-sm-12\">\n        <div ng-controller=\"ProgressDemoCtrl\">\n          <progressbar max=\"max\" value=\"dynamic\">\n            <span style=\"color:black; white-space:nowrap;\">{{dynamic}} / {{max}}</span>\n          </progressbar>\n        </div>\n      </div>\n    </div>\n  <script type=\"text/javascript\">\n     var app = angular.module('myApp', ['ui.bootstrap']);\n     app.controller('ProgressDemoCtrl', function ($scope) {\n       $scope.max = 100;\n       $scope.dynamic = 50;\n     });\n  </script>\n  </body>\n</html>" "<html>...<script src=\"angular.js\"></script></html>" nil nil nil nil nil nil)
                       ("html5" "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta name=\"description\" content=\"\" />\n    <title>${1:mytitle}</title>\n    <style type=\"text/css\"></style>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js\"></script>\n    <script type=\"text/javascript\">\n      Modernizr.load([{\n        test: Modernizr.mq('only all'),\n        nope: '//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js'\n      }]);\n    </script>\n  </head>\n  <body>\n    <p>First name: <input data-bind=\"value: firstName\" /></p>\n    <p>Last name: <input data-bind=\"value: lastName\" /></p>\n\n    <p>Full name: <strong data-bind=\"text: fullName\"></strong></p>\n    <p>First name: <strong data-bind=\"text: firstName\">todo</strong></p>\n    <p>Last name: <strong data-bind=\"text: lastName\">todo</strong></p>\n\n    <button data-bind=\"click: capitalizeLastName\">Go caps</button>\n    $0\n\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js\"></script>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/knockout/3.1.0/knockout-min.js\"></script>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/knockout-validation/1.0.2/knockout.validation.min.js\"></script>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/knockout-sortable/0.8.1/knockout-sortable.min.js\"></script>\n    <script type=\"text/javascript\">\n    $(document).ready(function (){\n      // This is a simple *viewmodel* - JavaScript that defines the data and behavior of your UI\n      function AppViewModel() {\n        this.firstName = ko.observable(\"Bert\");\n        this.lastName = ko.observable(\"Bertington\");\n    \n        this.fullName = ko.computed(function() {\n          return this.firstName() + \" \" + this.lastName();  \n        }, this);\n    \n        this.capitalizeLastName = function() {\n          var currentVal = this.lastName();    // Read the current value\n          this.lastName(currentVal.toUpperCase()); // Write back a modified value\n        };\n      }\n    \n      // Activates knockout.js\n      ko.applyBindings(new AppViewModel());\n    \n      console.log(\"jquery is working\");\n    });\n    </script>\n  </body>\n</html>\n" "<html>...<script src=\"knockout.js\"></script></html>" nil nil nil nil nil nil)
                       ("html5" "<!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <meta name=\"description\" content=\"\" />\n    <title>${1:mytitle}</title>\n    <style type=\"text/css\"></style>\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js\"></script>\n    <script type=\"text/javascript\">\n      Modernizr.load([{\n        test: Modernizr.mq('only all'),\n        nope: '//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js'\n      }]);\n    </script>\n  </head>\n  <body>\n    $0\n    <script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/zepto/1.1.2/zepto.min.js\"></script>\n    <script type=\"text/javascript\">\n      $(document).ready(function (){\n        alert(\"zepto is working\");\n      });\n    </script>\n  </body>\n</html>\n" "<html>...<script src=\"zepto.js\"></script></html>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"${1://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.9.0/jquery.validate.js}\"></script>\n" "<script src=\"jquery.validate.js\">...</script>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"${1://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.10.0/jquery-ui.js}\"></script>\n" "<script src=\"jquery-ui.js\">...</script>" nil nil nil nil nil nil)
                       ("label" "<label class=\"${1:className}\" for=\"${2:domID}\">${3:labelText}</label>\n$0\n" "label" nil nil nil nil nil nil)
                       ("lo" "<%= debug @${1:object} %>" "<%= debug @object %> (RoR)" nil nil nil nil nil nil)
                       ("reqjs" "<script data-main=\"${1:scripts}/main\" src=\"${1:$(yas-substr yas-text \"[^: ]*\")}/require.js\" type=\"text/javascript\"></script>\n" "require.js" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.16/angular${1:.min}.js\"></script>" "<script src=\"angular.js\">...</script>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/knockout/3.1.0/knockout-min.js\"></script>\n<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/knockout-validation/1.0.2/knockout.validation.min.js\"></script>" "<script src=\"knockout.js\">...</script>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.2/raphael-min.js\"></script>\n" "<script src=\"raphael.js\">...</script>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"//cdnjs.cloudflare.com/ajax/libs/zepto/1.1.2/zepto.min.js\"></script>\n" "<script src=\"zepto.js\">...</script>" nil nil nil nil nil nil)
                       ("script" "<script type=\"text/javascript\" src=\"${1://cdnjs.cloudflare.com/ajax/libs/jquery/1.8.2/jquery.js}\"></script>\n" "<script src=\"jquery.js\">...</script>" nil nil nil nil nil nil)
                       ("select" "<select name=\"${1:some_name}\" id=\"${1:$(yas/substr yas-text \"[^ ]*\")}\">\n<option value=\"${2:value1}\">${2:$(yas/substr yas-text \"[^ ]*\")}</option>\n<option value=\"${3:value2}\">${3:$(yas/substr yas-text \"[^ ]*\")}</option>\n$0\n</select>" "Select Box" nil nil nil nil nil nil)))


;;; Snippet definitions:
;;;
(yas-define-snippets 'rhtml-mode
                     '(("tef" "<${1:@}= ${2:function}( ${3:e} ) $1>$0\n" "template eval function" nil nil nil nil nil nil)
                       ("te" "<${1:@}= $0 $1>\n" "template eval" nil nil nil nil nil nil)
                       ("teach" "<${1:@} ${2:_.each} (${3:arr}, function(${4:e}) { $1>\n  $0\n<$1 }); $1>\n" "template for each" nil nil nil nil nil nil)
                       ("tife" "<${1:@} if (${2:true}) { $1>\n  $0\n<$1 } else { $1>\n<$1 } $1>\n" "template if else" nil nil nil nil nil nil)
                       ("tif" "<${1:@} if (${2:true}) { $1>\n<$1 } $1>\n" "template if" nil nil nil nil nil nil)))


;;; Do not edit! File generated at Thu May 28 14:17:45 2015
