;;; Compiled snippets and support files for `cmake-mode'
;;; Snippet definitions:
;;;
(yas-define-snippets 'cmake-mode
                     '(("main" "project(main)\ncmake_minimum_required(VERSION 2.6)\n\nset(TARGET_NAME main)\nset(TYPE \"\")\n\nset( CPP_SOURCES\n  main.cpp\n  )\n\nset( H_SOURCES\n  main.hpp\n  )\n\nset(SOURCES\n  \\${CPP_SOURCES}\n  \\${H_SOURCES}\n  )\n\nset(INC\n  \\${CMAKE_CURRENT_SOURCE_DIR}\n  )\n\ninclude_directories(\\${INC})\n\nif(UNIX)\n  add_definitions(-Wno-write-strings)\nendif()\n\nadd_executable(\\${TARGET_NAME} \\${TYPE} \\${SOURCES})\n\nset(LIBS\n  )\n\ntarget_link_libraries(\\${TARGET_NAME} \\${LIBS})\n" "main (...)" nil nil nil nil nil nil)
                       ("wxmain" "project(${1:main})\ncmake_minimum_required(VERSION 2.6)\n\nset(CMAKE_CXX_FLAGS_DEBUG \"\\${CMAKE_CXX_FLAGS_DEBUG} -D__WXDEBUG__ -DWXDEBUG=1\")\n\nset(TARGET_NAME ${2:main})\nset(TYPE \"\")\n\nif(CMAKE_COMPILER_IS_GNUCC)\n  # needed for gcc 4.6+\n  set(CMAKE_CXX_FLAGS \"\\${CMAKE_CXX_FLAGS} -fpermissive\")\nendif()\n\nset( CPP_SRC\n  main.cpp\n  $0\n  )\n\nset( H_SRC\n   #main.hpp\n    )\n\nset(SRC\n  \\${CPP_SRC}\n  \\${H_SRC}\n  )\n\n# xrc -> xml, adv, html\n#set(wxWidgets_USE_LIBS xrc xml adv html core base)\n# I don't use XML stuff\nset(wxWidgets_USE_LIBS adv html core base)\nfind_package(wxWidgets REQUIRED)\ninclude(\\${wxWidgets_USE_FILE})\n\nset(INC\n  \\${CMAKE_CURRENT_SOURCE_DIR}\n  )\n\nif(UNIX AND NOT APPLE)\n  include(FindPkgConfig)\n  pkg_check_modules(GTK2 REQUIRED gtk+-2.0>=2.10)\n  set(INC \\${INC} \\${GTK2_INCLUDE_DIRS})\nendif()\n\n#add other librarie\ninclude_directories(\\${INC})\n\nif(UNIX)\n  add_definitions(-Wno-write-strings)\nendif()\n\nif(WIN32)\n  # WIN32 := subsystem is windows instead of console?\n  set(TYPE WIN32)\nendif()\n\nif(APPLE)\n   set(TYPE MACOSX_BUNDLE)\nendif()\n\nadd_executable(\\${TARGET_NAME} \\${TYPE} \\${SRC})\n\nset(LIBS\n  \\${wxWidgets_LIBRARIES}\n  )\n\nif(MINGW AND WIN32)\n  set(LIBS \\${LIBS} ole32 uuid oleaut32)\nendif()\n\ntarget_link_libraries(\\${TARGET_NAME} \\${LIBS})\n" "wxmain (...)" nil nil nil nil nil nil)))


;;; Do not edit! File generated at Thu May 28 14:17:45 2015
